export {
  faPlus,
  faUserShield,
  faCalendar,
  faCalendarPlus,
  faCalendarMinus,
  faCalendarAlt,
  faColumns,
  faChevronDown,
  faEdit,
  faCamera,
  faFileAlt,
  faMicroscope,
  faChevronLeft,
  faPills,
  faUser,
  faUserPlus,
  faUserMinus,
  faUsers,
  faMinus,
  faChevronRight,
  faSave,
  faCog,
  faChevronUp,
} from '@fortawesome/free-solid-svg-icons'
